id: A64216866
title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the Guru from
  Afar'
type: translation
pechas:
- IB44CA29C
- I0F939442
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:30:42.353609
  last_modified_at: 2023-01-04 11:30:42.353619
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  IB44CA29C/B5A0: D8A4
  I0F939442/A5EA: D8A4
